const APPLICATION_ID_LENGTH = 20;
const APPLICATION_NAME_LENGTH = 64;
const APPLICATION_DESCRIPTION_LENGTH = 256;
const APPLICATION_REDIRECT_URL_LENGTH = 256;

export {
  APPLICATION_ID_LENGTH,
  APPLICATION_NAME_LENGTH,
  APPLICATION_DESCRIPTION_LENGTH,
  APPLICATION_REDIRECT_URL_LENGTH,
};
