const USERS_ID_LENGTH = 24;
const USERS_USERNAME_MAX_LENGTH = 50;
const USERS_USERNAME_MIN_LENGTH = 3;
const USERS_PLACEHOLDER_USERNAME_KEY = "  "; // 2 spaces
const USERS_PLACEHOLDER_USERNAME_LENGTH = 12;
const USERS_USERNAME_INPUT_PATTERN = "^[a-zA-Z0-9_]+$";
const USERS_USERNAME_VALIDATION_MESSAGE =
  "Username must not contain spaces or special characters";

export {
  USERS_ID_LENGTH,
  USERS_USERNAME_MAX_LENGTH,
  USERS_USERNAME_MIN_LENGTH,
  USERS_PLACEHOLDER_USERNAME_KEY,
  USERS_PLACEHOLDER_USERNAME_LENGTH,
  USERS_USERNAME_INPUT_PATTERN,
  USERS_USERNAME_VALIDATION_MESSAGE,
};
