const USERS_ID_LENGTH = 24;
const USERS_USERNAME_MAX_LENGTH = 50;
const USER_USERNAME_MIN_LENGTH = 3;
const USERS_PLACEHOLDER_USERNAME_KEY = "  "; // 2 spaces
const USERS_PLACEHOLDER_USERNAME_LENGTH = 12;

export {
  USERS_ID_LENGTH,
  USERS_USERNAME_MAX_LENGTH,
  USER_USERNAME_MIN_LENGTH,
  USERS_PLACEHOLDER_USERNAME_KEY,
  USERS_PLACEHOLDER_USERNAME_LENGTH,
};
